name: Publish

on:
  push:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.15.4"
          regustry-url: https://registry.npmjs.org/
      - run: npm publish --acesses public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
